apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: dependencies
spec:
  schedule: "*/5 0-1,13-23 * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: deps
    templates:
    - name: deps
      dag:
        tasks:
        - name: dep-1
          template: python-container
          arguments:
            parameters: [{name: python-script, value: dependencies/dep_1.py}]
        - name: dep-2
          template: python-container
          arguments:
            parameters: [{name: python-script, value: dependencies/dep_2.py}]
        - name: dep-3
          template: python-container
          arguments:
            parameters: [{name: python-script, value: dependencies/dep_3.py}]
          dependencies: [dep-1]
        - name: dep-4
          template: python-container
          arguments:
            parameters: [{name: python-script, value: dependencies/dep_4.py}]

    - name: python-container
      inputs:
        parameters:
          - name: python-script
      container:
        image: zackbaker/k8_argo_test:latest
        command: [python, "{{inputs.parameters.python-script}}"]