apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: list-directory
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: list-directory
    templates:
    - name: list-directory
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["ls"]
