apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: workflow
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: count
    templates:
    - name: count
      dag:
        tasks:
        - name: count
          template: python-container
          arguments:
            parameters: [{name: python-script, value: count.py}]
        - name: coinflip
          template: python-container
          arguments:
            parameters: [{name: python-script, value: coinflip.py}]
        - name: tails
          dependencies: [coinflip]
          template: coinflip
          when: "{{tasks.coinflip.output.results}} == tails"
        # - name: heads
        #   dependencies: [coinflip]
        #   template: python-container
        #   when: "{{tasks.coinflip.output.results}} == heads"
        #   arguments:
        #     parameters: [{name: python-script, value: print('it is heads!')}]

    - name: python-container
      inputs:
        parameters:
          - name: python-script
      container:
        image: zackbaker/k8_argo_test:latest
        command: [python, "{{inputs.parameters.python-script}}"]