apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: workflow
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: workflow
    templates:
    - name: workflow
      container:
        image: zackbaker/k8_argo_test:latest
        command: [python, count.py]