apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: workflow
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  templates:
    - name: python-container
      container:
        image: zackbaker/k8_argo_test:latest
        command: [python, count.py]
  workflowSpec:
    entrypoint: count
    templates:
    - name: count
      template: python-container