apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: random-number-event-source
spec:
  type: file
  file:
    random-numbers:
      watchPathConfig:
        # directory to watch
        directory: "/mnt/file-store/"
        # path to watch
        pathRegexp: "(random_number.*)+(.txt)$"
      # type of the event
      # supported types are: CREATE, WRITE, REMOVE, RENAME, CHMOD
      eventType: "CREATE"