apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: random-number-generator
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: random-number-generator
    templates:
    - name: random-number-generator
      steps:
      - - name: generate-random-number
          template: gen-file

    - name: gen-file
      script:
        image: debian:9.4
        command: [bash]
        source: |
          DATE=$(date "+%b_%d_%Y") |
          TIMESTAMP=$(date "+%s") |
          NUMBER=$(($RANDOM%10000+10000)) |
          echo "$NUMBER" >> /mnt/file-store/random_number-${DATE}_${TIMESTAMP}.txt
        volumeMounts:
          - name: workdir
            mountPath: /mnt/file-store

    volumes:
      - name: workdir
        persistentVolumeClaim:
          claimName: file-store