apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: random-number-sensor
  labels:
    # sensor controller with instanceId "argo-events" will process this sensor
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: sensor
          image: argoproj/sensor:v0.13.0
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      gatewayName: file-gateway
      eventName: random-numbers
  subscription:
    http:
      port: 9300
  triggers:
    - template:
        name: random-number-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: random-number-
              spec:
                entrypoint: handle-num
                arguments:
                  parameters:
                    - name: file-path
                      value: "file_path" # will be overridden
                templates:
                  - name: handle-num
                    dag:
                      tasks:
                        # Task
                        - name: print-number
                          template: python-container-3
                          arguments:
                            parameters: [
                              {name: python-script, value: rand_number/print_random_number.py},
                              {name: file-path, value: "{{workflow.parameters.file-path}}"}
                            ]
                        # Task
                        - name: delete-file
                          dependencies: [print-number]
                          template: python-container-3
                          arguments:
                            parameters: [
                              {name: python-script, value: rand_number/delete_file.py},
                              {name: file-path, value: "{{workflow.parameters.file-path}}"}
                            ]
                  # Container template
                  - name: python-container-3
                    inputs:
                      parameters:
                        - name: python-script
                        - name: file-path
                    container:
                      image: zackbaker/k8_argo_test:latest
                      command: [python, "{{inputs.parameters.python-script}}"]
                      args: ["{{inputs.parameters.file-path}}"]
                      volumeMounts:
                        - mountPath: /mnt/file-store
                          name: file-store

                volumes:
                  - name: file-store
                    persistentVolumeClaim:
                      claimName: file-store

          parameters:
            - src:
                dependencyName: test-dep
                dataKey: name
              dest: spec.arguments.parameters.0.value