apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: dependencies
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  suspend: false
  workflowSpec:
    entrypoint: deps
    onExit: record-stats # Run stats template after DAG finishes
    templates:
      - name: deps # Shows dependencies in DAG
        dag:
          tasks:
            - name: dep-1
              template: python-container-3
              arguments:
                parameters: [{name: python-script, value: dependencies/dep_1.py}]
            - name: dep-2
              template: python-container-3
              arguments:
                parameters: [{name: python-script, value: dependencies/dep_2.py}]
              dependencies: [dep-1]
            - name: dep-3
              template: python-container-3
              arguments:
                parameters: [{name: python-script, value: dependencies/dep_3.py}]
              dependencies: [dep-2]
            - name: dep-4
              template: python-container-3
              arguments:
                parameters: [{name: python-script, value: dependencies/dep_4.py}]
              dependencies: [dep-2]
            - name: dep-5
              template: failure
              dependencies: [dep-4]

      - name: python-container-3 # python 3 container that accepts different scripts as arguments
        inputs:
          parameters:
            - name: python-script
        container:
          image: zackbaker/k8_argo_test:latest
          command: [python, "{{inputs.parameters.python-script}}"]
        retryStrategy:
          limit: 1

      - name: failure # purposely fails to show failure and retry counts for workflow stats
        container:
          image: debian:9.4
          command: ["exit(1)"]
        retryStrategy:
          limit: 1

      - name: record-stats # Exit template to record workflow stats
        inputs:
          parameters:
            - name: task_count
              value: 5 #TODO: set to task count from dag
        container:
          image: zackbaker/k8_argo_test:latest
          command: [python, workflow_stats.py]
          args: [
            "--workflow_name", "{{workflow.name}}",
            "--creation_time", "{{workflow.creationTimestamp}}",
            "--failures", "{{workflow.failures}}",
            "--task_count", "{{inputs.parameters.task_count}}",
          ]