apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: dependencies
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  suspend: false
  workflowSpec:
    entrypoint: deps
    onExit: record-stats
    metrics:
      prometheus:
        - name: exec_duration_gauge         # Metric name (will be prepended with "argo_workflows_")
          help: "Duration gauge by name"    # A help doc describing your metric. This is required.
          gauge:                            # The metric type. Available are "gauge", "histogram", and "counter".
            value: "{{workflow.duration}}"  # The value of your metric. It could be an Argo variable (see variables doc) or a literal value
    templates:
      - name: deps
        dag:
          tasks:
            - name: dep-1
              template: python-container-3
              arguments:
                parameters: [{name: python-script, value: dependencies/dep_1.py}]
            - name: dep-2
              template: python-container-3
              arguments:
                parameters: [{name: python-script, value: dependencies/dep_2.py}]
              dependencies: [dep-1]
            - name: dep-3
              template: python-container-3
              arguments:
                parameters: [{name: python-script, value: dependencies/dep_3.py}]
              dependencies: [dep-2]
            - name: dep-4
              template: python-container-3
              arguments:
                parameters: [{name: python-script, value: dependencies/dep_4.py}]
              dependencies: [dep-2]

      - name: python-container-3
        inputs:
          parameters:
            - name: python-script
        container:
          image: zackbaker/k8_argo_test:latest
          command: [python, "{{inputs.parameters.python-script}}"]

      - name: record-stats
        metrics:
        container:
          image: zackbaker/k8_argo_test:latest
          command: [python, workflow_stats.py]
          args: [
            "--workflow_name", "{{workflow.name}}",
            "--creation_time", "{{workflow.creationTimestamp}}",
            "--duration", "{{metrics.prometheus.exec_duration_guage}}",
            "--failures", "{{workflow.failures}}"
          ]