apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: parallelism-limit
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    entrypoint: parallelism-limit
    parallelism: 2
    templates:
    - name: parallelism-limit
      steps:
      - - name: sleep
          template: sleep
          withItems:
          - this
          - workflow
          - should
          - take
          - at
          - least
          - 60
          - seconds
          - to
          - complete

    - name: sleep
      container:
        image: alpine:latest
        command: [sh, -c, sleep 10]
