apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: random-number-generator
  namespace: argo-events
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: random-number-generator
    templates:
    - name: random-number-generator
      steps:
      - - name: generate-random-number
          template: gen-file

    - name: gen-file
      script:
        image: debian:9.4
        command: [bash]
        source: |
          FILENAME=random_number- |
          CURRENT_TIME=$(date "+%Y.%m.%d-%H.%M.%S") |
          NUMBER=$(($RANDOM%10000+10000)) |
          echo "Creating file random_number-$CURRENT_TIME.txt" |
          echo "$NUMBER" >> /mnt/file-store/$FILENAME$CURRENT_TIME.txt
        volumeMounts:
          - name: workdir
            mountPath: /mnt/file-store

    volumes:
      - name: workdir
        persistentVolumeClaim:
          claimName: file-store